'use client';
// ============================================================
// VoiceLanguageDemo — interactive voice × language sampler.
//
// Outer tabs: 5 AI voices (Ara, Eve, Leo, Rx, Sal)
// Inner buttons: 7 languages (EN ES IT AR FA HY RU)
//
// Audio files served from /audio/voices/<voice>_<lang>.mp3
// Generated by: pnpm tsx scripts/generate-voice-language-samples.ts
// ============================================================
import { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import { Play, Pause, RotateCcw } from 'lucide-react';
import {
  VOICES, LANGUAGES, VOICE_IDS, LANG_CODES, getVoiceSample,
  type VoiceId, type LangCode,
} from '@/lib/voice-samples';

// ── Timing constants (same as SampleCallPlayer) ───────────────
/** Approximate seconds per AI character at ~150 wpm. */
const SECONDS_PER_AI_CHAR = 0.083;
/** Fixed pause duration allotted to each caller turn in the UI. */
const CALLER_BUBBLE_DURATION_S = 1.2;

/** Compute cumulative end-times for each line of a sample. */
function computeLineEndTimes(lines: Array<{ role: 'ai' | 'caller'; text: string }>): number[] {
  const out: number[] = [];
  let cursor = 0;
  for (const line of lines) {
    cursor += line.role === 'ai'
      ? line.text.length * SECONDS_PER_AI_CHAR
      : CALLER_BUBBLE_DURATION_S;
    out.push(cursor);
  }
  return out;
}

// ── Player card ───────────────────────────────────────────────
function VoicePlayer({ voice, lang }: { voice: VoiceId; lang: LangCode }) {
  const sample = getVoiceSample(voice, lang);
  const [playing, setPlaying] = useState(false);
  const [visibleLines, setVisibleLines] = useState(0);
  const [audioMissing, setAudioMissing] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  const lineEndTimes = useMemo(() => computeLineEndTimes(sample.lines), [sample]);
  const audioSrc = `/audio/voices/${voice}_${lang}.mp3`;
  const langMeta = LANGUAGES[lang];
  const voiceMeta = VOICES[voice];

  // Reset whenever voice or lang changes.
  useEffect(() => {
    const audio = audioRef.current;
    if (audio) {
      audio.pause();
      audio.currentTime = 0;
    }
    setPlaying(false);
    setVisibleLines(0);
    setAudioMissing(false);
  }, [voice, lang]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [visibleLines]);

  const handleTimeUpdate = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;
    const t = audio.currentTime;
    let count = 0;
    for (const endTime of lineEndTimes) {
      if (t >= endTime - 0.3) count += 1;
      else break;
    }
    if (count !== visibleLines) setVisibleLines(count);
  }, [lineEndTimes, visibleLines]);

  const handleEnded = useCallback(() => {
    setPlaying(false);
    setVisibleLines(sample.lines.length);
  }, [sample.lines.length]);

  const handleError = useCallback(() => {
    setAudioMissing(true);
    setPlaying(false);
  }, []);

  const handlePlay = useCallback(() => {
    if (audioMissing) return;
    const audio = audioRef.current;
    if (!audio) return;
    audio.play().then(
      () => setPlaying(true),
      () => setAudioMissing(true)
    );
  }, [audioMissing]);

  const handlePause = useCallback(() => {
    audioRef.current?.pause();
    setPlaying(false);
  }, []);

  const handleReset = useCallback(() => {
    const audio = audioRef.current;
    if (audio) { audio.pause(); audio.currentTime = 0; }
    setPlaying(false);
    setVisibleLines(0);
  }, []);

  useEffect(() => () => { audioRef.current?.pause(); }, []);

  // RTL languages
  const isRtl = lang === 'ar' || lang === 'fa' || lang === 'hy';

  return (
    <div className="bg-white rounded-2xl border border-cream-200 overflow-hidden shadow-sm">
      {/* Hidden audio */}
      <audio
        ref={audioRef}
        src={audioSrc}
        preload="none"
        onTimeUpdate={handleTimeUpdate}
        onEnded={handleEnded}
        onError={handleError}
      />

      {/* Header */}
      <div className="flex items-center justify-between gap-3 px-5 py-4 border-b border-cream-200">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-brand-600 flex items-center justify-center shrink-0">
            <span className="text-white font-serif text-base font-bold">{voiceMeta.label[0]}</span>
          </div>
          <div>
            <div className="flex items-center gap-2">
              <p className="text-sm font-bold text-cream-900">{voiceMeta.label}</p>
              <span className="text-lg">{langMeta.flag}</span>
              <span className="text-xs text-cream-500">{langMeta.label}</span>
              <span className="text-[10px] bg-cream-100 text-cream-500 px-2 py-0.5 rounded-full">~25s</span>
            </div>
            <p className="text-xs text-cream-500 mt-0.5">{voiceMeta.description}</p>
          </div>
        </div>

        <div className="flex items-center gap-1.5 shrink-0">
          {visibleLines > 0 && (
            <button
              onClick={handleReset}
              className="p-2 rounded-lg hover:bg-cream-100 text-cream-500 hover:text-cream-800 transition-colors"
              title="Reset"
            >
              <RotateCcw size={14} />
            </button>
          )}
          <button
            onClick={playing ? handlePause : handlePlay}
            disabled={audioMissing}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-brand-600 hover:bg-brand-700 text-white text-xs font-semibold transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
          >
            {playing ? <Pause size={13} /> : <Play size={13} />}
            {playing ? 'Pause' : visibleLines > 0 ? 'Resume' : 'Play'}
          </button>
        </div>
      </div>

      {/* Transcript */}
      <div className="p-4 bg-cream-50 max-h-64 overflow-y-auto rounded-b-2xl">
        {audioMissing ? (
          <p className="text-xs text-center py-6 text-cream-400">
            🎙️ Audio not yet generated.{' '}
            <a href="/demo" className="text-brand-500 hover:underline font-medium">
              Try the live AI demo →
            </a>
          </p>
        ) : visibleLines === 0 ? (
          <p className="text-xs text-center py-6 text-cream-400">
            ▶ Press Play to hear {voiceMeta.label} speaking {langMeta.label}
          </p>
        ) : (
          <div className="space-y-2.5" dir={isRtl ? 'rtl' : 'ltr'}>
            {sample.lines.slice(0, visibleLines).map((line, i) => (
              <div
                key={i}
                className={`flex gap-2.5 ${line.role === 'caller' ? 'justify-end' : 'justify-start'}`}
                style={{ animation: 'fadeIn 0.3s ease' }}
              >
                {line.role === 'ai' && (
                  <div className="w-6 h-6 rounded-full bg-brand-600 text-white flex items-center justify-center shrink-0 mt-0.5 text-[10px] font-bold">
                    AI
                  </div>
                )}
                <div className={`max-w-[82%] rounded-xl px-3 py-2 text-xs leading-relaxed ${
                  line.role === 'ai'
                    ? 'bg-brand-50 text-brand-900 border border-brand-100'
                    : 'bg-white text-cream-700 border border-cream-200'
                }`}>
                  {line.text}
                </div>
                {line.role === 'caller' && (
                  <div className="w-6 h-6 rounded-full bg-cream-200 text-cream-700 flex items-center justify-center shrink-0 mt-0.5 text-[10px] font-bold">
                    You
                  </div>
                )}
              </div>
            ))}
            {playing && visibleLines < sample.lines.length && (
              <div className="flex gap-1 pl-8 py-1">
                {[0, 1, 2].map((i) => (
                  <span
                    key={i}
                    className="w-1.5 h-1.5 rounded-full bg-brand-400"
                    style={{ animation: `pulse 1s ease ${i * 0.2}s infinite` }}
                  />
                ))}
              </div>
            )}
            <div ref={bottomRef} />
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="px-5 py-2 border-t border-cream-100 bg-white">
        <p className="text-[10px] text-cream-400 text-center">
          {voiceMeta.label} voice · {langMeta.label}
        </p>
      </div>
    </div>
  );
}

// ── Public export ─────────────────────────────────────────────
export function VoiceLanguageDemo() {
  const [activeVoice, setActiveVoice] = useState<VoiceId>('ara');
  const [activeLang, setActiveLang] = useState<LangCode>('en');

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6">
      {/* Section header */}
      <div className="text-center mb-10">
        <div className="inline-flex items-center gap-2 bg-brand-50 border border-brand-100 rounded-full px-4 py-1.5 text-sm text-brand-600 font-medium mb-4">
          🌐 Multilingual AI
        </div>
        <h2 className="text-3xl md:text-4xl font-black text-cream-900 tracking-tight mb-3">
          Every voice. Every language.
        </h2>
        <p className="text-cream-600 text-base max-w-xl mx-auto">
          Choose a voice and language to hear your AI receptionist in action — fluent in 7 languages, across 5 distinct voices.
        </p>
      </div>

      {/* Voice selector */}
      <div className="mb-6">
        <p className="text-xs font-semibold text-cream-500 uppercase tracking-widest mb-3 text-center">Choose a voice</p>
        <div className="flex flex-wrap justify-center gap-2">
          {VOICE_IDS.map((v) => {
            const meta = VOICES[v];
            return (
              <button
                key={v}
                onClick={() => setActiveVoice(v)}
                className={`flex flex-col items-center px-5 py-3 rounded-xl border text-sm font-semibold transition-all ${
                  activeVoice === v
                    ? 'bg-brand-600 border-brand-600 text-white shadow-md shadow-brand-600/20'
                    : 'bg-white border-cream-200 text-cream-700 hover:border-brand-300 hover:text-brand-600'
                }`}
              >
                <span className="font-bold">{meta.label}</span>
                <span className={`text-[10px] font-normal mt-0.5 ${activeVoice === v ? 'text-brand-200' : 'text-cream-400'}`}>
                  {meta.description}
                </span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Language selector */}
      <div className="mb-8">
        <p className="text-xs font-semibold text-cream-500 uppercase tracking-widest mb-3 text-center">Choose a language</p>
        <div className="flex flex-wrap justify-center gap-2">
          {LANG_CODES.map((l) => {
            const meta = LANGUAGES[l];
            return (
              <button
                key={l}
                onClick={() => setActiveLang(l)}
                className={`flex items-center gap-1.5 px-4 py-2 rounded-full border text-sm font-medium transition-all ${
                  activeLang === l
                    ? 'bg-cream-900 border-cream-900 text-white'
                    : 'bg-white border-cream-200 text-cream-700 hover:border-cream-400 hover:text-cream-900'
                }`}
              >
                <span className="text-base leading-none">{meta.flag}</span>
                <span>{meta.label}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Player */}
      <VoicePlayer key={`${activeVoice}_${activeLang}`} voice={activeVoice} lang={activeLang} />

    </div>
  );
}
